try{
data = "Content"
let data ;
}catch(error){
    console.log(error.message); 
}